# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AiUi1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1336, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_main = QtWidgets.QLabel(self.centralwidget)
        self.bg_main.setGeometry(QtCore.QRect(-60, -40, 1481, 891))
        self.bg_main.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_main.setText("")
        self.bg_main.setObjectName("bg_main")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(410, 90, 511, 501))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("GIF/83ec7dae7e76751eecca2adcf0dcfc49.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(-80, -30, 631, 161))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("deco/3ab74962b138cb7396156fd96d0f6408.gif"))
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(750, 590, 591, 161))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("deco/Untitled design (2).gif"))
        self.gif_3.setScaledContents(False)
        self.gif_3.setObjectName("gif_3")
        self.bg_start = QtWidgets.QLabel(self.centralwidget)
        self.bg_start.setGeometry(QtCore.QRect(20, 390, 241, 61))
        self.bg_start.setText("")
        self.bg_start.setPixmap(QtGui.QPixmap("button/button_1.png"))
        self.bg_start.setScaledContents(True)
        self.bg_start.setObjectName("bg_start")
        self.pb_start = QtWidgets.QPushButton(self.centralwidget)
        self.pb_start.setGeometry(QtCore.QRect(30, 400, 181, 51))
        self.pb_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka\";\n"
"color: rgb(255, 255, 255);")
        self.pb_start.setObjectName("pb_start")
        self.bg_exit = QtWidgets.QLabel(self.centralwidget)
        self.bg_exit.setGeometry(QtCore.QRect(20, 470, 241, 61))
        self.bg_exit.setText("")
        self.bg_exit.setPixmap(QtGui.QPixmap("button/button_1.png"))
        self.bg_exit.setScaledContents(True)
        self.bg_exit.setObjectName("bg_exit")
        self.pb_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pb_exit.setGeometry(QtCore.QRect(30, 480, 181, 51))
        self.pb_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka\";\n"
"color: rgb(255, 255, 255);")
        self.pb_exit.setObjectName("pb_exit")
        self.tb_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_time.setGeometry(QtCore.QRect(930, 10, 131, 71))
        self.tb_time.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 20pt \"Sitka\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.tb_time.setObjectName("tb_time")
        self.tb_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_date.setGeometry(QtCore.QRect(1080, 10, 231, 71))
        self.tb_date.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 20pt \"Sitka\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.tb_date.setObjectName("tb_date")
        self.bg_resp = QtWidgets.QLabel(self.centralwidget)
        self.bg_resp.setGeometry(QtCore.QRect(930, 90, 391, 431))
        self.bg_resp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bg_resp.setText("")
        self.bg_resp.setObjectName("bg_resp")
        self.AiUi = QtWidgets.QLabel(self.centralwidget)
        self.AiUi.setGeometry(QtCore.QRect(950, 60, 131, 101))
        self.AiUi.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 26pt \"Sitka\";")
        self.AiUi.setObjectName("AiUi")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(30, 570, 241, 111))
        self.gif_4.setStyleSheet("border-radius:none;")
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("deco/01.gif"))
        self.gif_4.setScaledContents(False)
        self.gif_4.setObjectName("gif_4")
        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(260, 570, 241, 111))
        self.gif_5.setStyleSheet("border-radius:none;")
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap("deco/01.gif"))
        self.gif_5.setScaledContents(False)
        self.gif_5.setObjectName("gif_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 550, 491, 151))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.terminalOutputbox = QtWidgets.QTextEdit(self.centralwidget)
        self.terminalOutputbox.setGeometry(QtCore.QRect(940, 140, 371, 371))
        self.terminalOutputbox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.terminalOutputbox.setObjectName("terminalOutputbox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 570, 231, 111))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 570, 241, 111))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.label_3.raise_()
        self.bg_main.raise_()
        self.gif_1.raise_()
        self.gif_2.raise_()
        self.gif_3.raise_()
        self.bg_start.raise_()
        self.pb_start.raise_()
        self.bg_exit.raise_()
        self.pb_exit.raise_()
        self.bg_resp.raise_()
        self.tb_time.raise_()
        self.tb_date.raise_()
        self.AiUi.raise_()
        self.label.raise_()
        self.gif_5.raise_()
        self.gif_4.raise_()
        self.terminalOutputbox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_start.setText(_translate("MainWindow", "START"))
        self.pb_exit.setText(_translate("MainWindow", "EXIT"))
        self.AiUi.setText(_translate("MainWindow", "A.i.U.i"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
